version: "3.9"
services:
  web_app:
    build: .
    ports:
      - "80:3000"
      - "443:443"
    volumes:
      - .:/app

  mongodb:
    image: mongo
    volumes:
      - mongo:/data/db
      - /etc/letsencrypt:/etc/letsencrypt

volumes:
  mongo:

