version: "3.9"
services:
  web_app:
    build: .
    ports:
      - "80:3000"
      - "443:443"
    volumes:
      - .:/app
      - certbot-etc:/etc/letsencrypt

  mongodb:
    image: mongo
    volumes:
      - mongo:/data/db

volumes:
  mongo:
  certbot-etc:
